// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: lab.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Enums ---
type Peligrosidad int32

const (
	Peligrosidad_BAJA  Peligrosidad = 0
	Peligrosidad_MEDIA Peligrosidad = 1
	Peligrosidad_ALTA  Peligrosidad = 2
)

// Enum value maps for Peligrosidad.
var (
	Peligrosidad_name = map[int32]string{
		0: "BAJA",
		1: "MEDIA",
		2: "ALTA",
	}
	Peligrosidad_value = map[string]int32{
		"BAJA":  0,
		"MEDIA": 1,
		"ALTA":  2,
	}
)

func (x Peligrosidad) Enum() *Peligrosidad {
	p := new(Peligrosidad)
	*p = x
	return p
}

func (x Peligrosidad) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Peligrosidad) Descriptor() protoreflect.EnumDescriptor {
	return file_lab_proto_enumTypes[0].Descriptor()
}

func (Peligrosidad) Type() protoreflect.EnumType {
	return &file_lab_proto_enumTypes[0]
}

func (x Peligrosidad) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Peligrosidad.Descriptor instead.
func (Peligrosidad) EnumDescriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{0}
}

type EstadoPirata int32

const (
	EstadoPirata_BUSCADO   EstadoPirata = 0
	EstadoPirata_CAPTURADO EstadoPirata = 1
	EstadoPirata_EN_CAMINO EstadoPirata = 2
	EstadoPirata_ENTREGADO EstadoPirata = 3
	EstadoPirata_PERDIDO   EstadoPirata = 4
)

// Enum value maps for EstadoPirata.
var (
	EstadoPirata_name = map[int32]string{
		0: "BUSCADO",
		1: "CAPTURADO",
		2: "EN_CAMINO",
		3: "ENTREGADO",
		4: "PERDIDO",
	}
	EstadoPirata_value = map[string]int32{
		"BUSCADO":   0,
		"CAPTURADO": 1,
		"EN_CAMINO": 2,
		"ENTREGADO": 3,
		"PERDIDO":   4,
	}
)

func (x EstadoPirata) Enum() *EstadoPirata {
	p := new(EstadoPirata)
	*p = x
	return p
}

func (x EstadoPirata) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstadoPirata) Descriptor() protoreflect.EnumDescriptor {
	return file_lab_proto_enumTypes[1].Descriptor()
}

func (EstadoPirata) Type() protoreflect.EnumType {
	return &file_lab_proto_enumTypes[1]
}

func (x EstadoPirata) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstadoPirata.Descriptor instead.
func (EstadoPirata) EnumDescriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{1}
}

type MetodoEntrega int32

const (
	MetodoEntrega_MARINA   MetodoEntrega = 0
	MetodoEntrega_SUBMUNDO MetodoEntrega = 1
)

// Enum value maps for MetodoEntrega.
var (
	MetodoEntrega_name = map[int32]string{
		0: "MARINA",
		1: "SUBMUNDO",
	}
	MetodoEntrega_value = map[string]int32{
		"MARINA":   0,
		"SUBMUNDO": 1,
	}
)

func (x MetodoEntrega) Enum() *MetodoEntrega {
	p := new(MetodoEntrega)
	*p = x
	return p
}

func (x MetodoEntrega) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetodoEntrega) Descriptor() protoreflect.EnumDescriptor {
	return file_lab_proto_enumTypes[2].Descriptor()
}

func (MetodoEntrega) Type() protoreflect.EnumType {
	return &file_lab_proto_enumTypes[2]
}

func (x MetodoEntrega) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetodoEntrega.Descriptor instead.
func (MetodoEntrega) EnumDescriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{2}
}

// --- Mensajes ---
type Pirata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa    uint64                 `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	Peligrosidad  Peligrosidad           `protobuf:"varint,4,opt,name=peligrosidad,proto3,enum=sistema.Peligrosidad" json:"peligrosidad,omitempty"`
	Estado        EstadoPirata           `protobuf:"varint,5,opt,name=estado,proto3,enum=sistema.EstadoPirata" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pirata) Reset() {
	*x = Pirata{}
	mi := &file_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pirata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pirata) ProtoMessage() {}

func (x *Pirata) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pirata.ProtoReflect.Descriptor instead.
func (*Pirata) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{0}
}

func (x *Pirata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pirata) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pirata) GetRecompensa() uint64 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *Pirata) GetPeligrosidad() Peligrosidad {
	if x != nil {
		return x.Peligrosidad
	}
	return Peligrosidad_BAJA
}

func (x *Pirata) GetEstado() EstadoPirata {
	if x != nil {
		return x.Estado
	}
	return EstadoPirata_BUSCADO
}

type ListaPiratas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piratas       []*Pirata              `protobuf:"bytes,1,rep,name=piratas,proto3" json:"piratas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaPiratas) Reset() {
	*x = ListaPiratas{}
	mi := &file_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaPiratas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPiratas) ProtoMessage() {}

func (x *ListaPiratas) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPiratas.ProtoReflect.Descriptor instead.
func (*ListaPiratas) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{1}
}

func (x *ListaPiratas) GetPiratas() []*Pirata {
	if x != nil {
		return x.Piratas
	}
	return nil
}

type SolicitudCaptura struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IdPirata               string                 `protobuf:"bytes,1,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	NombreCazarrecompensas string                 `protobuf:"bytes,2,opt,name=nombre_cazarrecompensas,json=nombreCazarrecompensas,proto3" json:"nombre_cazarrecompensas,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SolicitudCaptura) Reset() {
	*x = SolicitudCaptura{}
	mi := &file_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudCaptura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudCaptura) ProtoMessage() {}

func (x *SolicitudCaptura) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudCaptura.ProtoReflect.Descriptor instead.
func (*SolicitudCaptura) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudCaptura) GetIdPirata() string {
	if x != nil {
		return x.IdPirata
	}
	return ""
}

func (x *SolicitudCaptura) GetNombreCazarrecompensas() string {
	if x != nil {
		return x.NombreCazarrecompensas
	}
	return ""
}

type ResultadoCaptura struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoCaptura) Reset() {
	*x = ResultadoCaptura{}
	mi := &file_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoCaptura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoCaptura) ProtoMessage() {}

func (x *ResultadoCaptura) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoCaptura.ProtoReflect.Descriptor instead.
func (*ResultadoCaptura) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{3}
}

func (x *ResultadoCaptura) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoCaptura) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Transporte struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IdPirata               string                 `protobuf:"bytes,1,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	Metodo                 MetodoEntrega          `protobuf:"varint,2,opt,name=metodo,proto3,enum=sistema.MetodoEntrega" json:"metodo,omitempty"` // MARINA o SUBMUNDO
	NombreCazarrecompensas string                 `protobuf:"bytes,3,opt,name=nombre_cazarrecompensas,json=nombreCazarrecompensas,proto3" json:"nombre_cazarrecompensas,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Transporte) Reset() {
	*x = Transporte{}
	mi := &file_lab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transporte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transporte) ProtoMessage() {}

func (x *Transporte) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transporte.ProtoReflect.Descriptor instead.
func (*Transporte) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{4}
}

func (x *Transporte) GetIdPirata() string {
	if x != nil {
		return x.IdPirata
	}
	return ""
}

func (x *Transporte) GetMetodo() MetodoEntrega {
	if x != nil {
		return x.Metodo
	}
	return MetodoEntrega_MARINA
}

func (x *Transporte) GetNombreCazarrecompensas() string {
	if x != nil {
		return x.NombreCazarrecompensas
	}
	return ""
}

type ResultadoTransporte struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EstadoFinal        EstadoPirata           `protobuf:"varint,1,opt,name=estado_final,json=estadoFinal,proto3,enum=sistema.EstadoPirata" json:"estado_final,omitempty"`
	RecompensaEsperada uint64                 `protobuf:"varint,2,opt,name=recompensa_esperada,json=recompensaEsperada,proto3" json:"recompensa_esperada,omitempty"`
	Detalle            string                 `protobuf:"bytes,3,opt,name=detalle,proto3" json:"detalle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResultadoTransporte) Reset() {
	*x = ResultadoTransporte{}
	mi := &file_lab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoTransporte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoTransporte) ProtoMessage() {}

func (x *ResultadoTransporte) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoTransporte.ProtoReflect.Descriptor instead.
func (*ResultadoTransporte) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{5}
}

func (x *ResultadoTransporte) GetEstadoFinal() EstadoPirata {
	if x != nil {
		return x.EstadoFinal
	}
	return EstadoPirata_BUSCADO
}

func (x *ResultadoTransporte) GetRecompensaEsperada() uint64 {
	if x != nil {
		return x.RecompensaEsperada
	}
	return 0
}

func (x *ResultadoTransporte) GetDetalle() string {
	if x != nil {
		return x.Detalle
	}
	return ""
}

type EstadoCazarrecompensas struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NombreCazarrecompensas string                 `protobuf:"bytes,1,opt,name=nombre_cazarrecompensas,json=nombreCazarrecompensas,proto3" json:"nombre_cazarrecompensas,omitempty"`
	Reputacion             float32                `protobuf:"fixed32,2,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	TotalGanado            uint64                 `protobuf:"varint,3,opt,name=total_ganado,json=totalGanado,proto3" json:"total_ganado,omitempty"`
	Historial              []string               `protobuf:"bytes,4,rep,name=historial,proto3" json:"historial,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EstadoCazarrecompensas) Reset() {
	*x = EstadoCazarrecompensas{}
	mi := &file_lab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoCazarrecompensas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoCazarrecompensas) ProtoMessage() {}

func (x *EstadoCazarrecompensas) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoCazarrecompensas.ProtoReflect.Descriptor instead.
func (*EstadoCazarrecompensas) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{6}
}

func (x *EstadoCazarrecompensas) GetNombreCazarrecompensas() string {
	if x != nil {
		return x.NombreCazarrecompensas
	}
	return ""
}

func (x *EstadoCazarrecompensas) GetReputacion() float32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

func (x *EstadoCazarrecompensas) GetTotalGanado() uint64 {
	if x != nil {
		return x.TotalGanado
	}
	return 0
}

func (x *EstadoCazarrecompensas) GetHistorial() []string {
	if x != nil {
		return x.Historial
	}
	return nil
}

type AlertaActividad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`                             // e.j "Alta actividad en el Submundo detectada"
	NivelRiesgo   int32                  `protobuf:"varint,2,opt,name=nivel_riesgo,json=nivelRiesgo,proto3" json:"nivel_riesgo,omitempty"` // podría ir de 1 a 10, por ejemplo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertaActividad) Reset() {
	*x = AlertaActividad{}
	mi := &file_lab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertaActividad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertaActividad) ProtoMessage() {}

func (x *AlertaActividad) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertaActividad.ProtoReflect.Descriptor instead.
func (*AlertaActividad) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{7}
}

func (x *AlertaActividad) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *AlertaActividad) GetNivelRiesgo() int32 {
	if x != nil {
		return x.NivelRiesgo
	}
	return 0
}

type EntregaPirata struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NombreCazarrecompensas string                 `protobuf:"bytes,1,opt,name=nombre_cazarrecompensas,json=nombreCazarrecompensas,proto3" json:"nombre_cazarrecompensas,omitempty"`
	Pirata                 *Pirata                `protobuf:"bytes,2,opt,name=pirata,proto3" json:"pirata,omitempty"`
	Reputacion             float32                `protobuf:"fixed32,3,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	Metodo                 MetodoEntrega          `protobuf:"varint,4,opt,name=metodo,proto3,enum=sistema.MetodoEntrega" json:"metodo,omitempty"` // Método para decidir si es Marina o Submundo
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntregaPirata) Reset() {
	*x = EntregaPirata{}
	mi := &file_lab_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaPirata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaPirata) ProtoMessage() {}

func (x *EntregaPirata) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaPirata.ProtoReflect.Descriptor instead.
func (*EntregaPirata) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{8}
}

func (x *EntregaPirata) GetNombreCazarrecompensas() string {
	if x != nil {
		return x.NombreCazarrecompensas
	}
	return ""
}

func (x *EntregaPirata) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

func (x *EntregaPirata) GetReputacion() float32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

func (x *EntregaPirata) GetMetodo() MetodoEntrega {
	if x != nil {
		return x.Metodo
	}
	return MetodoEntrega_MARINA
}

type ResultadoEntrega struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Aceptado         bool                   `protobuf:"varint,1,opt,name=aceptado,proto3" json:"aceptado,omitempty"`
	RecompensaPagada uint64                 `protobuf:"varint,2,opt,name=recompensa_pagada,json=recompensaPagada,proto3" json:"recompensa_pagada,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResultadoEntrega) Reset() {
	*x = ResultadoEntrega{}
	mi := &file_lab_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoEntrega) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoEntrega) ProtoMessage() {}

func (x *ResultadoEntrega) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoEntrega.ProtoReflect.Descriptor instead.
func (*ResultadoEntrega) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{9}
}

func (x *ResultadoEntrega) GetAceptado() bool {
	if x != nil {
		return x.Aceptado
	}
	return false
}

func (x *ResultadoEntrega) GetRecompensaPagada() uint64 {
	if x != nil {
		return x.RecompensaPagada
	}
	return 0
}

var File_lab_proto protoreflect.FileDescriptor

const file_lab_proto_rawDesc = "" +
	"\n" +
	"\tlab.proto\x12\asistema\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x01\n" +
	"\x06Pirata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x04R\n" +
	"recompensa\x129\n" +
	"\fpeligrosidad\x18\x04 \x01(\x0e2\x15.sistema.PeligrosidadR\fpeligrosidad\x12-\n" +
	"\x06estado\x18\x05 \x01(\x0e2\x15.sistema.EstadoPirataR\x06estado\"9\n" +
	"\fListaPiratas\x12)\n" +
	"\apiratas\x18\x01 \x03(\v2\x0f.sistema.PirataR\apiratas\"h\n" +
	"\x10SolicitudCaptura\x12\x1b\n" +
	"\tid_pirata\x18\x01 \x01(\tR\bidPirata\x127\n" +
	"\x17nombre_cazarrecompensas\x18\x02 \x01(\tR\x16nombreCazarrecompensas\"B\n" +
	"\x10ResultadoCaptura\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\x92\x01\n" +
	"\n" +
	"Transporte\x12\x1b\n" +
	"\tid_pirata\x18\x01 \x01(\tR\bidPirata\x12.\n" +
	"\x06metodo\x18\x02 \x01(\x0e2\x16.sistema.MetodoEntregaR\x06metodo\x127\n" +
	"\x17nombre_cazarrecompensas\x18\x03 \x01(\tR\x16nombreCazarrecompensas\"\x9a\x01\n" +
	"\x13ResultadoTransporte\x128\n" +
	"\festado_final\x18\x01 \x01(\x0e2\x15.sistema.EstadoPirataR\vestadoFinal\x12/\n" +
	"\x13recompensa_esperada\x18\x02 \x01(\x04R\x12recompensaEsperada\x12\x18\n" +
	"\adetalle\x18\x03 \x01(\tR\adetalle\"\xb2\x01\n" +
	"\x16EstadoCazarrecompensas\x127\n" +
	"\x17nombre_cazarrecompensas\x18\x01 \x01(\tR\x16nombreCazarrecompensas\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x02 \x01(\x02R\n" +
	"reputacion\x12!\n" +
	"\ftotal_ganado\x18\x03 \x01(\x04R\vtotalGanado\x12\x1c\n" +
	"\thistorial\x18\x04 \x03(\tR\thistorial\"N\n" +
	"\x0fAlertaActividad\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12!\n" +
	"\fnivel_riesgo\x18\x02 \x01(\x05R\vnivelRiesgo\"\xc1\x01\n" +
	"\rEntregaPirata\x127\n" +
	"\x17nombre_cazarrecompensas\x18\x01 \x01(\tR\x16nombreCazarrecompensas\x12'\n" +
	"\x06pirata\x18\x02 \x01(\v2\x0f.sistema.PirataR\x06pirata\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x03 \x01(\x02R\n" +
	"reputacion\x12.\n" +
	"\x06metodo\x18\x04 \x01(\x0e2\x16.sistema.MetodoEntregaR\x06metodo\"[\n" +
	"\x10ResultadoEntrega\x12\x1a\n" +
	"\baceptado\x18\x01 \x01(\bR\baceptado\x12+\n" +
	"\x11recompensa_pagada\x18\x02 \x01(\x04R\x10recompensaPagada*-\n" +
	"\fPeligrosidad\x12\b\n" +
	"\x04BAJA\x10\x00\x12\t\n" +
	"\x05MEDIA\x10\x01\x12\b\n" +
	"\x04ALTA\x10\x02*U\n" +
	"\fEstadoPirata\x12\v\n" +
	"\aBUSCADO\x10\x00\x12\r\n" +
	"\tCAPTURADO\x10\x01\x12\r\n" +
	"\tEN_CAMINO\x10\x02\x12\r\n" +
	"\tENTREGADO\x10\x03\x12\v\n" +
	"\aPERDIDO\x10\x04*)\n" +
	"\rMetodoEntrega\x12\n" +
	"\n" +
	"\x06MARINA\x10\x00\x12\f\n" +
	"\bSUBMUNDO\x10\x012\xb8\x04\n" +
	"\x0fGobiernoMundial\x12F\n" +
	"\x15ListarPiratasBuscados\x12\x16.google.protobuf.Empty\x1a\x15.sistema.ListaPiratas\x12H\n" +
	"\x10RegistrarCaptura\x12\x19.sistema.SolicitudCaptura\x1a\x19.sistema.ResultadoCaptura\x12O\n" +
	"\x14ActualizarReputacion\x12\x1f.sistema.EstadoCazarrecompensas\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\rAlertarMarina\x12\x18.sistema.AlertaActividad\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x1fConsultarEstadoCazarrecompensas\x12\x1f.sistema.EstadoCazarrecompensas\x1a\x1f.sistema.EstadoCazarrecompensas\x12W\n" +
	"\x19RegistrarCazarrecompensas\x12\x1f.sistema.EstadoCazarrecompensas\x1a\x19.sistema.ResultadoCaptura\x12A\n" +
	"\x16ActualizarEstadoPirata\x12\x0f.sistema.Pirata\x1a\x16.google.protobuf.Empty2\xd3\x02\n" +
	"\x10Cazarrecompensas\x12F\n" +
	"\x11TransportarPirata\x12\x13.sistema.Transporte\x1a\x1c.sistema.ResultadoTransporte\x12J\n" +
	"\x0fConsultarEstado\x12\x16.google.protobuf.Empty\x1a\x1f.sistema.EstadoCazarrecompensas\x12F\n" +
	"\x15ConsultarListaPiratas\x12\x16.google.protobuf.Empty\x1a\x15.sistema.ListaPiratas\x12c\n" +
	"\x1fConsultarEstadoCazarrecompensas\x12\x1f.sistema.EstadoCazarrecompensas\x1a\x1f.sistema.EstadoCazarrecompensas2\xa5\x02\n" +
	"\x06Marina\x12B\n" +
	"\rRecibirPirata\x12\x16.sistema.EntregaPirata\x1a\x19.sistema.ResultadoEntrega\x12A\n" +
	"\rRecibirAlerta\x12\x18.sistema.AlertaActividad\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x15ConsultarListaPiratas\x12\x16.google.protobuf.Empty\x1a\x15.sistema.ListaPiratas\x12L\n" +
	"\x11NotificarGobierno\x12\x1f.sistema.EstadoCazarrecompensas\x1a\x16.google.protobuf.Empty2\x96\x01\n" +
	"\bSubmundo\x12B\n" +
	"\rComprarPirata\x12\x16.sistema.EntregaPirata\x1a\x19.sistema.ResultadoEntrega\x12F\n" +
	"\x15InterceptarTransporte\x12\x0f.sistema.Pirata\x1a\x1c.sistema.ResultadoTransporteB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_lab_proto_rawDescOnce sync.Once
	file_lab_proto_rawDescData []byte
)

func file_lab_proto_rawDescGZIP() []byte {
	file_lab_proto_rawDescOnce.Do(func() {
		file_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)))
	})
	return file_lab_proto_rawDescData
}

var file_lab_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lab_proto_goTypes = []any{
	(Peligrosidad)(0),              // 0: sistema.Peligrosidad
	(EstadoPirata)(0),              // 1: sistema.EstadoPirata
	(MetodoEntrega)(0),             // 2: sistema.MetodoEntrega
	(*Pirata)(nil),                 // 3: sistema.Pirata
	(*ListaPiratas)(nil),           // 4: sistema.ListaPiratas
	(*SolicitudCaptura)(nil),       // 5: sistema.SolicitudCaptura
	(*ResultadoCaptura)(nil),       // 6: sistema.ResultadoCaptura
	(*Transporte)(nil),             // 7: sistema.Transporte
	(*ResultadoTransporte)(nil),    // 8: sistema.ResultadoTransporte
	(*EstadoCazarrecompensas)(nil), // 9: sistema.EstadoCazarrecompensas
	(*AlertaActividad)(nil),        // 10: sistema.AlertaActividad
	(*EntregaPirata)(nil),          // 11: sistema.EntregaPirata
	(*ResultadoEntrega)(nil),       // 12: sistema.ResultadoEntrega
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_lab_proto_depIdxs = []int32{
	0,  // 0: sistema.Pirata.peligrosidad:type_name -> sistema.Peligrosidad
	1,  // 1: sistema.Pirata.estado:type_name -> sistema.EstadoPirata
	3,  // 2: sistema.ListaPiratas.piratas:type_name -> sistema.Pirata
	2,  // 3: sistema.Transporte.metodo:type_name -> sistema.MetodoEntrega
	1,  // 4: sistema.ResultadoTransporte.estado_final:type_name -> sistema.EstadoPirata
	3,  // 5: sistema.EntregaPirata.pirata:type_name -> sistema.Pirata
	2,  // 6: sistema.EntregaPirata.metodo:type_name -> sistema.MetodoEntrega
	13, // 7: sistema.GobiernoMundial.ListarPiratasBuscados:input_type -> google.protobuf.Empty
	5,  // 8: sistema.GobiernoMundial.RegistrarCaptura:input_type -> sistema.SolicitudCaptura
	9,  // 9: sistema.GobiernoMundial.ActualizarReputacion:input_type -> sistema.EstadoCazarrecompensas
	10, // 10: sistema.GobiernoMundial.AlertarMarina:input_type -> sistema.AlertaActividad
	9,  // 11: sistema.GobiernoMundial.ConsultarEstadoCazarrecompensas:input_type -> sistema.EstadoCazarrecompensas
	9,  // 12: sistema.GobiernoMundial.RegistrarCazarrecompensas:input_type -> sistema.EstadoCazarrecompensas
	3,  // 13: sistema.GobiernoMundial.ActualizarEstadoPirata:input_type -> sistema.Pirata
	7,  // 14: sistema.Cazarrecompensas.TransportarPirata:input_type -> sistema.Transporte
	13, // 15: sistema.Cazarrecompensas.ConsultarEstado:input_type -> google.protobuf.Empty
	13, // 16: sistema.Cazarrecompensas.ConsultarListaPiratas:input_type -> google.protobuf.Empty
	9,  // 17: sistema.Cazarrecompensas.ConsultarEstadoCazarrecompensas:input_type -> sistema.EstadoCazarrecompensas
	11, // 18: sistema.Marina.RecibirPirata:input_type -> sistema.EntregaPirata
	10, // 19: sistema.Marina.RecibirAlerta:input_type -> sistema.AlertaActividad
	13, // 20: sistema.Marina.ConsultarListaPiratas:input_type -> google.protobuf.Empty
	9,  // 21: sistema.Marina.NotificarGobierno:input_type -> sistema.EstadoCazarrecompensas
	11, // 22: sistema.Submundo.ComprarPirata:input_type -> sistema.EntregaPirata
	3,  // 23: sistema.Submundo.InterceptarTransporte:input_type -> sistema.Pirata
	4,  // 24: sistema.GobiernoMundial.ListarPiratasBuscados:output_type -> sistema.ListaPiratas
	6,  // 25: sistema.GobiernoMundial.RegistrarCaptura:output_type -> sistema.ResultadoCaptura
	13, // 26: sistema.GobiernoMundial.ActualizarReputacion:output_type -> google.protobuf.Empty
	13, // 27: sistema.GobiernoMundial.AlertarMarina:output_type -> google.protobuf.Empty
	9,  // 28: sistema.GobiernoMundial.ConsultarEstadoCazarrecompensas:output_type -> sistema.EstadoCazarrecompensas
	6,  // 29: sistema.GobiernoMundial.RegistrarCazarrecompensas:output_type -> sistema.ResultadoCaptura
	13, // 30: sistema.GobiernoMundial.ActualizarEstadoPirata:output_type -> google.protobuf.Empty
	8,  // 31: sistema.Cazarrecompensas.TransportarPirata:output_type -> sistema.ResultadoTransporte
	9,  // 32: sistema.Cazarrecompensas.ConsultarEstado:output_type -> sistema.EstadoCazarrecompensas
	4,  // 33: sistema.Cazarrecompensas.ConsultarListaPiratas:output_type -> sistema.ListaPiratas
	9,  // 34: sistema.Cazarrecompensas.ConsultarEstadoCazarrecompensas:output_type -> sistema.EstadoCazarrecompensas
	12, // 35: sistema.Marina.RecibirPirata:output_type -> sistema.ResultadoEntrega
	13, // 36: sistema.Marina.RecibirAlerta:output_type -> google.protobuf.Empty
	4,  // 37: sistema.Marina.ConsultarListaPiratas:output_type -> sistema.ListaPiratas
	13, // 38: sistema.Marina.NotificarGobierno:output_type -> google.protobuf.Empty
	12, // 39: sistema.Submundo.ComprarPirata:output_type -> sistema.ResultadoEntrega
	8,  // 40: sistema.Submundo.InterceptarTransporte:output_type -> sistema.ResultadoTransporte
	24, // [24:41] is the sub-list for method output_type
	7,  // [7:24] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_lab_proto_init() }
func file_lab_proto_init() {
	if File_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_lab_proto_goTypes,
		DependencyIndexes: file_lab_proto_depIdxs,
		EnumInfos:         file_lab_proto_enumTypes,
		MessageInfos:      file_lab_proto_msgTypes,
	}.Build()
	File_lab_proto = out.File
	file_lab_proto_goTypes = nil
	file_lab_proto_depIdxs = nil
}
